version: '3'

services:
  ganache:
    image: trufflesuite/ganache
    command: ganache-cli -h 0.0.0.0 -i 1 -p 8545
    ports:
      - "8545:8545"

  truffle:
    build: .
    depends_on:
      - ganache

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile.production
    ports:
      - "3000:3000"
    depends_on:
      - ganache
      - truffle
    environment:
      NODE_ENV: production
