version: '3'

services:
  ganache:
    image: trufflesuite/ganache-cli
    command: ganache-cli -i 1 -p 8545
    ports:
      - "8545:8545"

  frontend:
    build: .
    command: truffle migrate
    ports:
      - "3000:3000"
      - "8547:8545"
    depends_on:
      - ganache
    environment:
      NODE_ENV: production
