name: Solidity CI
on:
  push:
    paths:
      - 'contracts/**'
      - '.github/workflows/solidity.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    env:
      test_dir: .
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Upgrade NPM
      run: npm install -g npm
    - run: npm i -g solhint
    - name: Lint contracts
      run: solhint "contracts/*.sol"
      working-directory: ${{ env.test_dir }}
    - run: npm i -g ganache truffle
    - run: npm ci
      continue-on-error: true
      working-directory: ${{ env.test_dir }}
    - name: test
      run: |
        npm run ganache &
        truffle test
      working-directory: ${{ env.test_dir }}
